name: kynikos
favicon: null
layout_spectrum: 0.00769
typography_spectrum: 0.79451
title: kynikos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72617631-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a29572'
    - '#01010d'
    - '#c0b997'
    - '#4c4c38'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
