name: kynikos
favicon: null
layout_spectrum: 0.728821630589664
typography_spectrum: 0.8617541138082743
title: kynikos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72617631-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.37473875330761075
  lightness: 0.5350026087835431
  saturation: 0.9440078365150839
  rhythmicContrast: 0.47157795587554574
purpose: []
