name: kynikos
favicon: null
layout_spectrum: 0.011151651851832867
typography_spectrum: 0.8783485305029899
title: kynikos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72617631-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.5034554947633296
  lightness: 0.4178511498030275
  saturation: 0.9141457627993077
  rhythmicContrast: 0.03740398236550391
purpose: []
