name: kynikos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55495
title: kynikos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a29572'
    - '#01010d'
    - '#c0b997'
    - '#4c4c38'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
